apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql-service
  labels:
    app: {{ .Release.Name }}-mysql
spec:
  ports:
  - port: {{ .Values.servicePort | default 3306 }}
    targetPort: {{ .Values.containerPort | default 3306 }}
    name: mysql
  - port: 8080
    targetPort: 80
    name: phpmyadmin
  selector:
    app: {{ .Release.Name }}-mysql
  type: {{ .Values.serviceType | default "ClusterIP" }}