apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-apache
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-apache
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-apache
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-apache
    spec:
      containers:
      - name: {{ .Release.Name }}-apache
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.containerPort | default 80 }}