apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-apache
  labels:
    app: {{ .Release.Name }}-apache
spec:
  ports:
  - port: {{ .Values.servicePort | default 80 }}
    targetPort: {{ .Values.containerPort | default 80 }}
  selector:
    app: {{ .Release.Name }}-apache
  type: {{ .Values.serviceType | default "ClusterIP" }}
