{{- if .Values.services }}
{{- range .Values.services }}
{{- if .enabled }}
---
{{- $relname := $.Release.Name -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $relname }}-{{ .name }}-mysql
  labels:
{{ include "mylabels" (dict "relname" $relname "envname" .name) | indent 4 }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: {{ $.Values.service.port }}
      name: mysql
    - port: 8080
      targetPort: 80
      name: phpmyadmin
  selector:
{{ include "mylabels"  (dict "relname" $relname "envname" .name) | indent 4 }}
{{- end }}
{{- end }}
{{- end }}