{{- if .Values.services }}
{{- range .Values.services }}
{{- if .enabled }}
---
{{- $relname := $.Release.Name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-{{ .name }}-mysql-secret
  labels:
{{ include "mylabels" (dict "relname" $relname "envname" .name) | indent 4 }}
type: Opaque
data:
  password: {{ randAlphaNum 16 | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}